### ISSUE TITLE
Add back auth scaffolding

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#44]
Need to relook at all the authentication scaffolding. Early days had a lot of rewrites in this.

We need to support controllers and routes for:

- [x] Login
- [x] Registration
- [x] Forgot password / Password resets (possibly need a new table for this called `password_resets`)
- [x] A generic home page when the user logs in.

**Comment by girardinsamuel** [comment]
Not sure why you would need a table to do password resets 🤔 ?
I guess we should stay "frontend agnostic" for the different views ? Or should we at least use Tailwind CSS ?

**Comment by josephmancuso** [comment]
> Not sure why you would need a table to do password resets

Sort of following in the foot steps of how Laravel does it. I suppose we don't really **need one** as we can still do it now. But I feel like it might be better to have a dedicated password resets to store the tokens. We could also better control the expirations of the token. Like password resets only valid for 24 hours or something.

**Comment by josephmancuso** [comment]
> I guess we should stay "frontend agnostic" for the different views ? Or should we at least use Tailwind CSS

Its a good question. I don't like being TOO opinionated on something like that. We could take a similar approach of what we did with M3 and make different presets like `jinja2` (default), `bootstrap`, `tailwind`. And then have something like:

```
python craft auth --preset tailwind
```

idk if I really want to maintaining all of these upgrades though between major releases ... idk. open for discussion lol. Have to balance what would be really cool as a framework and what we want to maintain.

**Comment by girardinsamuel** [comment]
>  I don't like being TOO opinionated on something like that
I agree ! I guess using the same approach would be ideal but then we would have to maintain the presets and also the auth presets and those are not really easy to maintain because there have some dependencies which are never up to date...

Maybe as Tailwind CSS seems to be used more and more and it's not a frontend framework this could be the one we will maintain for the auth scaffolding ?

For something more opiniated and complex, Laravel did Jetstream with different preset (Livewire and Inertia) but for CSS I guess they are using TailwindCSS.
